folio-org/mod-feesfines

- ramls/accountdata.json
- ramls/examples/transfer-type.sample
Trigger the generate-api-docs
Remove trailing spaces FOLIO-351
> FOLIO-903 api-docs config

- descriptors/DeploymentDescriptor-template.json
- descriptors/ModuleDescriptor-template.json
- src/main/resources/postgres-conf.json
Modify files for implementation
> Modify files for implementation

- ramls/examples/feefineaction.sample
- ramls/examples/feefineaction_collection.sample
- ramls/feefineactiondata.json
Added a new column titled "Payment method" [UIU-473](https://issues.folio.org/browse/UIU-473)
> Add paymentMethod

- ramls/accountdata.json
- ramls/examples/account.sample
- ramls/examples/account_collection.sample
- ramls/examples/feefine.sample
- ramls/examples/feefine_collection.sample
- ramls/feefinedata.json
- src/test/java/org/folio/modfeefinetest/RestVerticleIT.java
Modify resources feefines/ and accounts/
> Modify resources

- ramls/accountdata.json
- ramls/examples/account.sample
- ramls/examples/account_collection.sample
Add Due date and Returned date columns for [UIU-581](https://issues.folio.org/browse/UIU-581)
> Add columns for task UIU-581

- data/okapi-enable-feesfines.json
- ramls/examples/feefine.sample
- ramls/examples/feefine_collection.sample
- ramls/feefinedata.json
- src/main/java/org/folio/rest/utils/ValidationHelper.java
* Fix code smell.
* Modify resources owners an feefines.Ref [UIU-713](https://issues.folio.org/browse/UIU-713).
> Fix code smell

- NEWS.md
- ramls/examples/waive_collection.sample
- ramls/waivedataCollection.json
- src/main/java/org/folio/rest/impl/WaivesAPI.java
> Modify resource waives

- NEWS.md
- pom.xml
- ramls/examples/waive_collection.sample
- ramls/waivedataCollection.json
- src/main/java/org/folio/rest/impl/WaivesAPI.java
> Release 15.3.1

- NEWS.md
- data/okapi-enable-feesfines.json
- pom.xml
* Modify resorce waives.
* Update to RBM version.
> Update to RBM version

- NEWS.md
- src/main/java/org/folio/rest/impl/AccountsAPI.java
- src/main/java/org/folio/rest/impl/CommentsAPI.java
- src/main/java/org/folio/rest/impl/FeeFineActionsAPI.java
- src/main/java/org/folio/rest/impl/FeeFinesAPI.java
- src/main/java/org/folio/rest/impl/ManualBlocksAPI.java
- src/main/java/org/folio/rest/impl/OwnersAPI.java
- src/main/java/org/folio/rest/impl/PaymentsAPI.java
- src/main/java/org/folio/rest/impl/RefundsAPI.java
- src/main/java/org/folio/rest/impl/TransferCriteriaAPI.java
- src/main/java/org/folio/rest/impl/TransfersAPI.java
- src/main/java/org/folio/rest/impl/WaivesAPI.java
* Add rollback transaction to APIs. [MODFEE-10](https://issues.folio.org/browse/MODFEE-10)
> Unclosed database transaction

- pom.xml
> Add release

- .gitmodules
- NEWS.md
- pom.xml
- ramls/accountdata.json
- ramls/commentdata.json
- ramls/examples/owner.sample
- ramls/feefineactiondata.json
- ramls/manualblockdata.json
- ramls/ownerdata.json
- ramls/paymentdata.json
- ramls/refunddata.json
- ramls/transfer-criteriadata.json
- ramls/transferdata.json
- ramls/waivedata.json
- src/main/java/org/folio/rest/impl/AccountsAPI.java
- src/main/java/org/folio/rest/impl/CommentsAPI.java
- src/main/java/org/folio/rest/impl/FeeFineActionsAPI.java
- src/main/java/org/folio/rest/impl/FeeFinesAPI.java
- src/main/java/org/folio/rest/impl/ManualBlocksAPI.java
- src/main/java/org/folio/rest/impl/OwnersAPI.java
- src/main/java/org/folio/rest/impl/PaymentsAPI.java
- src/main/java/org/folio/rest/impl/RefundsAPI.java
- src/main/java/org/folio/rest/impl/TransferCriteriaAPI.java
- src/main/java/org/folio/rest/impl/TransfersAPI.java
- src/main/java/org/folio/rest/impl/WaivesAPI.java
- src/main/resources/templates/db_scripts/schema.json
- src/test/java/org/folio/modfeefinetest/RestVerticleIT.java
* Update 26.2.4 RMB version. [Version 25](https://github.com/folio-org/raml-module-builder/blob/master/doc/upgrading.md#version-25)
> Update RMB 26.2.4

- NEWS.md
- ramls/accountdata.json
- src/main/java/org/folio/rest/impl/AccountsAPI.java
- src/main/java/org/folio/rest/impl/CommentsAPI.java
- src/main/java/org/folio/rest/impl/FeeFineActionsAPI.java
- src/main/java/org/folio/rest/impl/FeeFinesAPI.java
- src/main/java/org/folio/rest/impl/ManualBlocksAPI.java
- src/main/java/org/folio/rest/impl/OwnersAPI.java
- src/main/java/org/folio/rest/impl/PaymentsAPI.java
- src/main/java/org/folio/rest/impl/RefundsAPI.java
- src/main/java/org/folio/rest/impl/TransferCriteriaAPI.java
- src/main/java/org/folio/rest/impl/TransfersAPI.java
- src/main/java/org/folio/rest/impl/WaivesAPI.java
* Fix ID POST to resources. Fixes [MODFEE-2](https://issues.folio.org/browse/MODFEE-2), [UIU-1150](https://issues.folio.org/browse/UIU-1150).
> Fix POST to resources

- descriptors/ModuleDescriptor-template.json
- pom.xml
- ramls/accounts.raml
- ramls/patronNotice.json
- src/main/java/org/folio/rest/client/PatronNoticeClient.java
- src/main/java/org/folio/rest/impl/AccountsAPI.java
- src/main/java/org/folio/rest/repository/FeeFineRepository.java
- src/main/java/org/folio/rest/repository/OwnerRepository.java
- src/main/java/org/folio/rest/service/PatronNoticeService.java
- src/test/java/org/folio/PatronNoticeTest.java
Resolves: MODFEE-11, MODFEE-12
1. Send patron notice for payment of fee/fine charge
2. Send patron notice for manual fee/fine charge
https://issues.folio.org/browse/MODFEE-11
https://issues.folio.org/browse/MODFEE-12
> [MODFEE-11 MODFEE-12] Send fee/fine patron notices

- descriptors/ModuleDescriptor-template.json
- ramls/examples/lost-item-fee-policies.json
- ramls/examples/lost-item-fee-policy.json
- ramls/period.json
We adding: 
* Modify Fee/Fine Lost Item Fee Policies. Refs [UIU-1156](https://issues.folio.org/browse/UIU-1156).
> Modify Fee/Fine Lost Item Fee Policies

- src/main/java/org/folio/rest/impl/OverdueFinePoliciesAPI.java
- src/main/java/org/folio/rest/utils/ErrorHelper.java
- src/test/java/org/folio/rest/impl/OverdueFinePoliciesAPITest.java
- src/test/java/org/folio/rest/utils/ErrorHelperTest.java
**Purpose**
Fix a bug in `mod-feesfines`
**Link**
[MODFEE-16](https://issues.folio.org/browse/MODFEE-16)
> [MODFEE-16] Error message not displaying when duplicate policy name entered

- src/main/java/org/folio/rest/impl/LostItemFeePoliciesAPI.java
- src/test/java/org/folio/rest/impl/LostItemFeePoliciesAPITest.java
**Purpose**
Fix a bug in `mod-feesfines`.
**Link**
[MODFEE-17](https://issues.folio.org/browse/MODFEE-17)
> [MODFEE-17] Error message not displaying when duplicate policy name entered

- src/main/java/org/folio/rest/impl/LostItemFeePoliciesAPI.java
- src/test/java/org/folio/rest/impl/LostItemFeePoliciesAPITest.java
**Purpose**
Fix a bug in `mod-feesfines`.
**Link**
[MODFEE-17](https://issues.folio.org/browse/MODFEE-17)
> [MODFEE-17] Fix unique policy name violation check

- src/main/java/org/folio/rest/impl/OverdueFinePoliciesAPI.java
- src/test/java/org/folio/rest/impl/OverdueFinePoliciesAPITest.java
**Purpose**
Fix a bug in `mod-feesfines`
**Link**
[MODFEE-16](https://issues.folio.org/browse/MODFEE-16)
> [MODFEE-16] Fix unique policy name violation check

- ramls/examples/feefineaction.sample
- ramls/examples/feefineaction_collection.sample
- ramls/feefineactiondata.json
- src/main/java/org/folio/rest/impl/FeeFineActionsAPI.java
- src/test/java/org/folio/PatronNoticeTest.java
- src/test/java/org/folio/rest/impl/FeeFineActionsAPITest.java
**Purpose**
Fix a bug in `mod-feesfines`
**Link**
[MODFEE-22](https://issues.folio.org/browse/MODFEE-22)
> MODFEE-22 Sending "new fee/fine" and "payment" notices when "Notify patron" unchecked

- pom.xml
- src/main/java/org/folio/rest/client/PatronNoticeClient.java
- src/main/java/org/folio/rest/impl/FeeFineActionsAPI.java
- src/main/java/org/folio/rest/impl/LostItemFeePoliciesAPI.java
- src/main/java/org/folio/rest/impl/OverdueFinePoliciesAPI.java
- src/main/java/org/folio/rest/repository/AccountRepository.java
- src/main/java/org/folio/rest/repository/FeeFineRepository.java
- src/main/java/org/folio/rest/repository/OwnerRepository.java
- src/main/java/org/folio/rest/utils/ErrorHelper.java
- src/test/java/org/folio/PatronNoticeTest.java
- src/test/java/org/folio/rest/impl/FeeFineActionsAPITest.java
- src/test/java/org/folio/rest/impl/LostItemFeePoliciesAPITest.java
- src/test/java/org/folio/rest/impl/OverdueFinePoliciesAPITest.java
- src/test/java/org/folio/rest/utils/ErrorHelperTest.java
Update RMB to v29.3.1, update Vert.x to v3.8.5
Resolves [MODFEE-36](https://issues.folio.org/browse/MODFEE-36).
> [MODFEE-36] Update RMB to v29.3.1

- reference-data/feefines/lost-item-fee.json
- reference-data/feefines/lost-item-processing-fee.json
- reference-data/feefines/overdue-fine.json
- reference-data/feefines/replacement-processing-fee.json
- src/main/java/org/folio/rest/impl/TenantRefAPI.java
- src/main/resources/templates/db_scripts/populate-feefines.sql
- src/main/resources/templates/db_scripts/schema.json
- src/test/java/org/folio/rest/impl/FeeFinesAPITest.java
- src/test/java/org/folio/rest/impl/TenantRefAPITest.java
Resolves [MODFEE-46](https://issues.folio.org/browse/MODFEE-46)
> [MODFEE-46] Load automatic fees/fines via SQL-script

- descriptors/ModuleDescriptor-template.json
- pom.xml
- src/main/java/org/folio/rest/client/InventoryClient.java
- src/main/java/org/folio/rest/domain/EventType.java
- src/main/java/org/folio/rest/impl/AccountsAPI.java
- src/main/java/org/folio/rest/impl/TenantRefAPI.java
- src/main/java/org/folio/rest/service/PubSubService.java
- src/main/java/org/folio/rest/utils/JsonHelper.java
- src/main/resources/MessagingDescriptor.json
- src/test/java/org/folio/rest/impl/APITests.java
- src/test/java/org/folio/rest/impl/AccountsAPITest.java
- src/test/java/org/folio/rest/impl/FeeFineActionsAPITest.java
- src/test/java/org/folio/rest/impl/FeeFinesAPITest.java
- src/test/java/org/folio/rest/impl/LostItemFeePoliciesAPITest.java
- src/test/java/org/folio/rest/impl/OverdueFinePoliciesAPITest.java
- src/test/java/org/folio/rest/impl/TenantRefAPITest.java
- src/test/java/org/folio/rest/utils/OkapiClient.java
**Purpose**
Introduce integration with mod-pubsub. Publish events when account is created, changed or deleted.
**Resolves**
[MODFEE-53](https://issues.folio.org/browse/MODFEE-53)
> MODFEE-53] Publish fee/fine balance change event

- pom.xml
- src/main/java/org/folio/rest/impl/AccountsAPI.java
- src/main/java/org/folio/rest/impl/CommentsAPI.java
- src/main/java/org/folio/rest/impl/FeeFineActionsAPI.java
- src/main/java/org/folio/rest/impl/FeeFinesAPI.java
- src/main/java/org/folio/rest/impl/ManualBlocksAPI.java
- src/main/java/org/folio/rest/impl/OwnersAPI.java
- src/main/java/org/folio/rest/impl/PaymentsAPI.java
- src/main/java/org/folio/rest/impl/RefundsAPI.java
- src/main/java/org/folio/rest/impl/TransferCriteriaAPI.java
- src/main/java/org/folio/rest/impl/TransfersAPI.java
- src/main/java/org/folio/rest/impl/WaivesAPI.java
- src/main/java/org/folio/rest/service/PatronNoticeService.java
- src/test/java/org/folio/PatronNoticeTest.java
- src/test/java/org/folio/rest/impl/FeeFineActionsAPITest.java
- src/test/java/org/folio/rest/impl/TenantRefAPITest.java
- Update to RMB v30
- Update vertx to 3.9.0
- Do all related changes according to RMB upgrading notes
Resolves: [MODFEE-59](https://issues.folio.org/browse/MODFEE-59)
> MODFEE-59 update RMB version to 30.0.0 and vertx to 3.9

- src/main/java/org/folio/rest/domain/EventType.java
- src/main/java/org/folio/rest/service/AccountEventPublisher.java
- src/main/resources/MessagingDescriptor.json
- src/test/java/org/folio/rest/impl/AccountsAPITest.java
Rename FF_BALANCE_CHANGED event to FEE_FINE_BALANCE_CHANGED.
Resolves [MODFEE-63](https://issues.folio.org/browse/MODFEE-63).
> [MODFEE-63] rename FF_BALANCE_CHANGED event to FEE_FINE_BALANCE_CHANGED

- ramls/feefineactions.raml
- ramls/user.json
- src/main/java/org/folio/rest/client/OkapiClient.java
- src/main/java/org/folio/rest/client/UsersClient.java
- src/main/java/org/folio/rest/domain/FeeFineNoticeContext.java
- src/main/java/org/folio/rest/impl/FeeFineActionsAPI.java
- src/main/java/org/folio/rest/service/PatronNoticeService.java
- src/test/java/org/folio/PatronNoticeTest.java
- src/test/java/org/folio/rest/client/UsersClientTest.java
- src/test/java/org/folio/rest/impl/FeeFineActionsAPITest.java
- src/test/java/org/folio/test/support/ApiTests.java
Resolves [MODFEE-66](https://issues.folio.org/browse/MODFEE-66)
> [MODFEE-66] enable user-related tokens for manual fee/fine patron notices

- pom.xml
Update RMB to fix [MODFEE-62](https://issues.folio.org/browse/MODFEE-62)
> Update RMB to v30.0.1

- src/main/java/org/folio/rest/service/AccountEventPublisher.java
- src/test/java/org/folio/rest/impl/AccountsAPITest.java
- Add loanId to the FEE_FINE_BALANCE_CHANGED event payload
- Update tests
Resolves: [MODFEE-71](https://issues.folio.org/browse/MODFEE-71)
> MODFEE-71 add loanId to the FEE_FINE_BALANCE_CHANGED event payload

- descriptors/ModuleDescriptor-template.json
- ramls/user.json
- src/test/java/org/folio/PatronNoticeTest.java
- Enable additional properties for User entity;
- Add permission for feefineactions;
Resolves: [MODFEE-89](https://issues.folio.org/browse/MODFEE-89)
> MODFEE-89 Enable addition properties for user, add permission

- src/main/java/org/folio/rest/utils/PatronNoticeBuilder.java
- src/test/java/org/folio/rest/impl/FeeFineActionsAPITest.java
- src/test/java/org/folio/rest/utils/PatronNoticeBuilderTest.java
- fix issue with decimal formatting for double values;
- update tests;
Resolves: [MODFEE-87](https://issues.folio.org/browse/MODFEE-87)
> [MODFEE-87] Add currency formatter

- descriptors/ModuleDescriptor-template.json
- ramls/accounts.raml
- src/main/java/org/folio/rest/impl/AccountsAPI.java
- src/test/java/org/folio/rest/impl/AccountsAPITest.java
- src/test/java/org/folio/rest/impl/AccountsActionChecksAPITests.java
- src/test/java/org/folio/rest/utils/ResourceClients.java
- src/test/java/org/folio/test/support/ApiTests.java
- src/test/java/org/folio/test/support/EntityBuilder.java
- create check-transfer endpoint;
- add validation;
- create tests;
Resolves: [MODFEE-81](https://issues.folio.org/browse/MODFEE-81)
> MODFEE-81 create check-transfer endpoint, add tests

- Dockerfile
- Jenkinsfile
- pom.xml
- src/test/java/org/folio/rest/impl/LostItemFeePoliciesAPITest.java
- src/test/java/org/folio/rest/impl/OverdueFinePoliciesAPITest.java
- src/test/java/org/folio/rest/utils/PatronNoticeBuilderTest.java
- upgrade to jdk 11;
- upgrade RMB to 31.0.2
Resolves: [MODFEE-103](https://issues.folio.org/browse/MODFEE-103)
> MODFEE-103 update RMB and jdk versions, fix tests

- descriptors/ModuleDescriptor-template.json
- ramls/accounts.raml
- ramls/actions/actionSuccessResponse.json
- src/main/java/org/folio/rest/domain/Action.java
- src/main/java/org/folio/rest/domain/MonetaryValue.java
- src/main/java/org/folio/rest/impl/AccountsAPI.java
- src/main/java/org/folio/rest/repository/FeeFineActionRepository.java
- src/main/java/org/folio/rest/service/action/ActionContext.java
- src/main/java/org/folio/rest/service/action/ActionService.java
- src/main/java/org/folio/rest/service/action/DefaultActionService.java
- src/main/java/org/folio/rest/service/action/PayActionService.java
- src/main/java/org/folio/rest/service/action/RefundActionService.java
- src/main/java/org/folio/rest/service/action/TransferActionService.java
- src/main/java/org/folio/rest/service/action/WaiveActionService.java
- src/main/java/org/folio/rest/service/action/validation/ActionValidationService.java
- src/main/java/org/folio/rest/service/action/validation/DefaultActionValidationService.java
- src/main/java/org/folio/rest/service/action/validation/RefundActionValidationService.java
- src/main/java/org/folio/rest/utils/ActionResultAdapter.java
- src/main/java/org/folio/rest/utils/FeeFineActionHelper.java
- src/test/java/org/folio/rest/impl/AccountsActionChecksAPITests.java
- src/test/java/org/folio/rest/impl/AccountsActionsAPITests.java
- src/test/java/org/folio/rest/impl/AccountsPayWaiveTransferAPITests.java
- src/test/java/org/folio/rest/impl/AccountsRefundAPITests.java
- src/test/java/org/folio/rest/utils/ResourceClients.java
- src/test/java/org/folio/test/support/EntityBuilder.java
- src/test/java/org/folio/test/support/matcher/FeeFineActionMatchers.java
Resolves [MODFEE-86](https://issues.folio.org/browse/MODFEE-86).
> [MODFEE-86] Create refund endpoint

- src/main/java/org/folio/rest/domain/Action.java
- src/main/java/org/folio/rest/impl/AccountsAPI.java
- src/main/java/org/folio/rest/service/action/CancelActionService.java
- src/main/java/org/folio/rest/service/action/validation/ActionValidationResult.java
- src/main/java/org/folio/rest/service/action/validation/ActionValidationService.java
- src/main/java/org/folio/rest/service/action/validation/CancelActionValidationService.java
- src/main/java/org/folio/rest/service/action/validation/DefaultActionValidationService.java
- src/main/java/org/folio/rest/service/action/validation/RefundActionValidationService.java
- src/test/java/org/folio/rest/impl/AccountsActionChecksAPITests.java
- src/test/java/org/folio/rest/impl/AccountsCancelActionAPITests.java
Resolves [MODFEE-86](https://issues.folio.org/browse/MODFEE-86).
> [MODFEE-86] Fix check-refund logic

- src/main/java/org/folio/rest/client/FeeFinePubSubClient.java
- src/main/java/org/folio/rest/client/InventoryClient.java
- src/main/java/org/folio/rest/client/OkapiClient.java
- src/main/java/org/folio/rest/client/PatronNoticeClient.java
- src/main/java/org/folio/rest/client/UsersClient.java
- src/main/java/org/folio/rest/client/WebClientProvider.java
- src/main/java/org/folio/rest/impl/AccountsAPI.java
- src/main/java/org/folio/rest/service/AccountUpdateService.java
- src/main/java/org/folio/rest/service/EventPublisher.java
- src/main/java/org/folio/rest/service/PatronNoticeService.java
- src/test/java/org/folio/rest/client/OkapiClientTest.java
Fix Leaked HTTP Clients and Connection Mananger
Create webclient only once!
> MODFEE-93: Leaked HTTP Clients and Connection Mananger

- .gitignore
- descriptors/ModuleDescriptor-template.json
- ramls/accounts-bulk.raml
- ramls/actions/bulkCheckActionRequest.json
- ramls/actions/bulkCheckActionResponse.json
- ramls/actions/checkActionRequest.json
- ramls/actions/checkActionResponse.json
- src/main/java/org/folio/rest/impl/AccountsAPI.java
- src/main/java/org/folio/rest/impl/AccountsBulkAPI.java
- src/main/java/org/folio/rest/repository/AccountRepository.java
- src/main/java/org/folio/rest/service/action/ActionService.java
- src/main/java/org/folio/rest/service/action/CancelActionService.java
- src/main/java/org/folio/rest/service/action/validation/ActionValidationService.java
- src/main/java/org/folio/rest/service/action/validation/CancelActionValidationService.java
- src/main/java/org/folio/rest/service/action/validation/DefaultActionValidationService.java
- src/main/java/org/folio/rest/service/action/validation/RefundActionValidationService.java
- src/main/java/org/folio/rest/utils/AccountHelper.java
- src/main/java/org/folio/rest/utils/ActionResultAdapter.java
- src/test/java/org/folio/rest/impl/AccountsAPITest.java
- src/test/java/org/folio/rest/impl/AccountsActionChecksAPITests.java
- src/test/java/org/folio/rest/impl/AccountsCancelActionAPITests.java
- src/test/java/org/folio/rest/impl/AccountsPayWaiveTransferAPITests.java
- src/test/java/org/folio/rest/impl/AccountsRefundAPITests.java
- src/test/java/org/folio/rest/utils/ResourceClients.java
- src/test/java/org/folio/test/support/EntityBuilder.java
Resolves [MODFEE-105](https://issues.folio.org/browse/MODFEE-105).
Allows to perform "bulk check pay" action (same as "check pay", but for multiple accounts).
> MODFEE-105 Create check-pay endpoint for multiple selected accounts

- descriptors/ModuleDescriptor-template.json
- ramls/accounts-bulk.raml
- src/main/java/org/folio/rest/impl/AccountsBulkAPI.java
- src/main/java/org/folio/rest/utils/ActionResultAdapter.java
- src/test/java/org/folio/rest/impl/AccountsActionChecksAPITests.java
- src/test/java/org/folio/rest/utils/ResourceClients.java
Create check-transfer and check-waive endpoint for multiple selected accounts. Based on #117
> Create check-transfer and check-waive endpoint for multiple selected accounts

- ramls/actions/bulkActionSuccessResponse.json
- src/main/java/org/folio/rest/impl/AccountsBulkAPI.java
- src/test/java/org/folio/rest/impl/AccountsBulkPayWaiveTransferAPITests.java
Additional pull request for MODFEE-108 - adding info about feeFineActions created during a bulk action to a successful response.
> MODFEE-108 Return a list of fee/fine actions

- descriptors/ModuleDescriptor-template.json
- ramls/accounts-bulk.raml
- ramls/actions/cancelBulkActionRequest.json
- src/main/java/org/folio/rest/impl/AccountsBulkAPI.java
- src/main/java/org/folio/rest/service/action/BulkActionService.java
- src/main/java/org/folio/rest/service/action/BulkCancelActionService.java
- src/main/java/org/folio/rest/service/action/validation/CancelActionValidationService.java
- src/main/java/org/folio/rest/utils/ActionResultAdapter.java
- src/main/java/org/folio/rest/utils/amountsplitter/DummyBulkSplitterStrategy.java
- src/main/java/org/folio/rest/utils/amountsplitter/EchoActionableAmounts.java
- src/test/java/org/folio/rest/impl/AccountsCancelActionAPITests.java
- src/test/java/org/folio/rest/utils/ResourceClients.java
Create cancel endpoint for multiple selected accounts
> Create cancel endpoint for multiple selected accounts

- descriptors/ModuleDescriptor-template.json
[MODFEE-124](Log Event Publisher for Fees/Fines flow) - Log Event Publisher for Fees/Fines flow
> MODFEE-124 - Log Event Publisher for Fees/Fines flow

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
PubSub permissions bug fix release (MODFEE-124)
> Bugfix release 15.9.1

- descriptors/ModuleDescriptor-template.json
- ramls/accountdata.json
- ramls/actions/actionFailureResponse.json
- ramls/actions/actionSuccessResponse.json
- ramls/actions/bulkActionFailureResponse.json
- ramls/actions/bulkActionSuccessResponse.json
- ramls/actions/bulkCheckActionRequest.json
- ramls/actions/bulkCheckActionResponse.json
- ramls/actions/cancelActionRequest.json
- ramls/actions/cancelBulkActionRequest.json
- ramls/actions/checkActionResponse.json
- ramls/actions/defaultActionRequest.json
- ramls/actions/defaultBulkActionRequest.json
- ramls/inventory/holdingsrecord.json
- ramls/inventory/instance.json
- ramls/inventory/item.json
- ramls/uuid.json
- src/main/java/org/folio/rest/impl/AccountsAPI.java
- src/test/java/org/folio/rest/impl/AccountsAPITest.java
Resolves [MODFEE-88](https://issues.folio.org/browse/MODFEE-88)
> [MODFEE-88] UUID fields should be validated against the UUID regex pattern

- src/main/java/org/folio/rest/domain/MonetaryValue.java
- src/main/java/org/folio/rest/exception/ActionException.java
- src/main/java/org/folio/rest/utils/amountsplitter/SplitEvenlyRecursively.java
- src/test/java/org/folio/rest/utils/amountsplitter/SplitEvenlyRecursivelyTest.java
Resolves [MODFEE-136](https://issues.folio.org/browse/MODFEE-136).
> [MODFEE-136] Fix amount splitting logic for bulk actions

- pom.xml
- src/test/java/org/folio/rest/impl/FeeFineActionsAPITest.java
Resolves [MODFEE-140](https://issues.folio.org/browse/MODFEE-140).
> MODFEE-140 Upgrade to RMB 31.1.5 and Vert.x 3.9.4

- src/main/resources/templates/db_scripts/schema.json
The issue surfaced during Bugfest Honeysuckle testing.
> MODFEE-141: add two missing indexes

- descriptors/ModuleDescriptor-template.json
- ramls/accounts.raml
- ramls/actions/actionSuccessResponse.json
- src/main/java/org/folio/rest/impl/AccountsAPI.java
- src/test/java/org/folio/rest/impl/AccountsCancelActionAPITests.java
- src/test/java/org/folio/rest/impl/AccountsPayWaiveTransferAPITests.java
- src/test/java/org/folio/rest/impl/AccountsRefundAPITests.java
Resolves [MODFEE-147](https://issues.folio.org/browse/MODFEE-147)
> [MODFEE-147] Return list of fee/fine actions created as a result of pay/waive/transfer/cancel/refund calls

- src/test/java/org/folio/rest/impl/FeeFineReportsAPITest.java
When I tried to merge https://github.com/folio-org/mod-feesfines/pull/154
into master, I discovered a large number of breaking tests in the master 
branch preventing the build.  It looks like a previous commit to master 
which I had  merged into my own code to update it had a number of failing 
tests-not sure how it was missed.  Jenkins didn't say boo to me until I 
initiated the merge.  I went into the test and figured out
that tests were failing because of some time and timezone based errors in
the tests themselves-the API was storing and returning the correct dates,
the test was formatting dates incorrectly or requesting data in the wrong
timeframe.  As a result, time values were not matching and tests were failing. 
I traced the errors and fixed the test code-it looks like they are …
> Fixing a lot of broken tests 

- ramls/reports/refundReportEntry.json
- src/main/java/org/folio/rest/service/report/RefundReportService.java
- src/test/java/org/folio/rest/impl/FeeFineReportsAPITest.java
- src/test/java/org/folio/test/support/matcher/RefundReportEntryMatcher.java
Resolves: [MODFEE-152](https://issues.folio.org/browse/MODFEE-152)
> MODFEE-152 Add fee/fine owner column to refund report, change paid/transferred columns logic

- src/main/java/org/folio/rest/service/report/RefundReportService.java
- src/main/java/org/folio/rest/utils/AccountHelper.java
- src/test/java/org/folio/rest/impl/FeeFineReportsAPITest.java
- src/test/java/org/folio/test/support/EntityBuilder.java
Resolves: [MODFEE-164](https://issues.folio.org/browse/MODFEE-164)
> MODFEE-164 Refund report fails when automatic refunds exist

- src/main/java/org/folio/rest/impl/FeeFineActionsAPI.java
> MODFEE-165 Code style changes

- src/main/java/org/folio/rest/impl/FeeFineActionsAPI.java
- src/test/java/org/folio/rest/impl/FeeFineActionsAPITest.java
- src/test/java/org/folio/test/support/matcher/FeeFineActionMatchers.java
Resolves [MODFEE-165](https://issues.folio.org/browse/MODFEE-165).
Field name was missing from the criteria for deleting fee/fine actions.
> MODFEE-165 DELETE feefineactions endpoint is broken

- ramls/reports/refundReportRequest.json
- src/main/java/org/folio/rest/impl/FeeFineReportsAPI.java
- src/main/java/org/folio/rest/repository/FeeFineActionRepository.java
- src/main/java/org/folio/rest/service/report/RefundReportService.java
- src/test/java/org/folio/rest/impl/FeeFineReportsAPITest.java
Resolves: [MODFEE-173](https://issues.folio.org/browse/MODFEE-173)
> MODFEE-173 Make start date and end date not required

- .gitignore
- descriptors/ModuleDescriptor-template.json
- pom.xml
- src/main/java/org/folio/rest/client/ConfigurationClient.java
- src/main/java/org/folio/rest/impl/AccountsAPI.java
- src/main/java/org/folio/rest/impl/AccountsBulkAPI.java
- src/main/java/org/folio/rest/impl/CommentsAPI.java
- src/main/java/org/folio/rest/impl/FeeFineActionsAPI.java
- src/main/java/org/folio/rest/impl/FeeFineReportsAPI.java
- src/main/java/org/folio/rest/impl/FeeFinesAPI.java
- src/main/java/org/folio/rest/impl/ManualBlocksAPI.java
- src/main/java/org/folio/rest/impl/OwnersAPI.java
- src/main/java/org/folio/rest/impl/PaymentsAPI.java
- src/main/java/org/folio/rest/impl/RefundsAPI.java
- src/main/java/org/folio/rest/impl/TenantRefAPI.java
- src/main/java/org/folio/rest/impl/TransferCriteriaAPI.java
- src/main/java/org/folio/rest/impl/TransfersAPI.java
- src/main/java/org/folio/rest/impl/WaivesAPI.java
- src/main/java/org/folio/rest/service/EventPublisher.java
- src/main/java/org/folio/rest/service/PatronNoticeService.java
- src/main/java/org/folio/rest/service/PubSubRegistrationService.java
- src/main/java/org/folio/rest/service/action/validation/ActionValidationService.java
- src/main/java/org/folio/rest/service/report/RefundReportService.java
- src/test/java/org/folio/migration/FeeFineTypesDefaultReferenceRecordsTest.java
- src/test/java/org/folio/modfeefinetest/RestVerticleIT.java
- src/test/java/org/folio/rest/impl/LostItemFeePoliciesAPITest.java
- src/test/java/org/folio/rest/impl/OverdueFinePoliciesAPITest.java
- src/test/java/org/folio/test/support/ApiTests.java
Resolves: [MODFEE-163](https://issues.folio.org/browse/MODFEE-163)
> MODFEE-163 Upgrade to RMB v32

- pom.xml
Resolves [MODPUBSUB-195](https://issues.folio.org/browse/MODPUBSUB-195).
> MODFEE-195 Update pub-sub version

- NEWS.md
- pom.xml
Resolves [MODFEE-191](https://issues.folio.org/browse/MODFEE-191).
> [MODFEE-191] Release 16.1.0

- src/main/java/org/folio/rest/service/report/DateBasedReportService.java
- src/main/java/org/folio/rest/service/report/FinancialTransactionsDetailReportService.java
- src/test/java/org/folio/rest/impl/FeeFineReportsAPITestBase.java
- src/test/java/org/folio/rest/impl/FinancialTransactionDetailReportTest.java
Fixes [MODFEE-201](https://issues.folio.org/browse/MODFEE-201)
Due date and Return date should be blank when account is not associated with any loan. Instead, current time is written to these fields.
> MODFEE-201 Financial transactions report - due date and return date issue

- src/main/java/org/folio/rest/service/action/RefundActionService.java
- src/test/java/org/folio/rest/impl/AccountsRefundAPITests.java
Currently refund does not change the fee/fine balance, while it should increase it.
Resolves [MODFEE-203](https://issues.folio.org/browse/MODFEE-203).
> [MODFEE-203] Refund should increase account balance

- src/main/java/org/folio/rest/domain/MonetaryValue.java
- src/main/java/org/folio/rest/repository/FeeFineActionRepository.java
- src/main/java/org/folio/rest/service/action/validation/RefundActionValidationService.java
- src/main/java/org/folio/rest/utils/FeeFineActionHelper.java
- src/test/java/org/folio/rest/impl/AccountsRefundAPITests.java
- src/test/java/org/folio/test/support/ApiTests.java
Resolves [MODFEE-203](https://issues.folio.org/browse/MODFEE-203)
> [MODFEE-203] Consider previously refunded amount when repeatedly refunding the same fee/fine

- ramls/accountdata.json
- ramls/charge.json
- ramls/feefineactiondata.json
- ramls/feefinedata.json
- ramls/lost-item-fee-policy.json
- ramls/overdue-fine-policy.json
- ramls/quantity.json
- ramls/transfer-criteriadata.json
https://issues.folio.org/browse/MODFEE-210
Added "type" : "number" everywhere with "javaType": "org.folio.rest.domain.MonetaryValue".
> MODFEE-210 adding type number

- NEWS.md
- pom.xml
Resolves [MODFEE-214](https://issues.folio.org/browse/MODFEE-214).
> [MODFEE-214] Release 17.0.0

- src/main/java/org/folio/rest/service/action/RefundActionService.java
- src/test/java/org/folio/rest/impl/AccountsRefundAPITests.java
Resolves [MODFEE-229](https://issues.folio.org/browse/MODFEE-229)
> [MODFEE-229] Refund changes status of account to Open

- NEWS.md
- pom.xml
- src/main/java/org/folio/rest/service/action/RefundActionService.java
- src/test/java/org/folio/rest/impl/AccountsRefundAPITests.java
Resolves: [MODFEE-231](https://issues.folio.org/browse/MODFEE-231)
> [MODFEE-231] Release v17.0.1

- pom.xml
https://issues.folio.org/browse/MODFEE-232
> MODFEE-232 Added log4j dependencies (version 2.16.0) into pom.xml

- NEWS.md
- pom.xml
Resolves [MODFEE-242](https://issues.folio.org/browse/MODFEE-242)
> [MODFEE-242] Release 17.1.0

- src/main/java/org/folio/rest/domain/AutomaticFeeFineType.java
- src/main/java/org/folio/rest/impl/FeeFinesAPI.java
- src/test/java/org/folio/rest/impl/FeeFinesAPITest.java
https://issues.folio.org/browse/MODFEE-243
> MODFEE-243 Prevent deleting/updating required FeeFines

- ramls/accountdata.json
- src/test/java/org/folio/rest/domain/AccountPaymentStatusTest.java
[MODFEE-245](https://issues.folio.org/browse/MODFEE-245)
_Missing account payment status 'Suspended claim returned'_
> MODFEE-245: Missing account payment status 'Suspended claim returned'

- descriptors/ModuleDescriptor-template.json
- ramls/accounts.raml
- ramls/actions/actionSuccessResponse.json
- src/main/java/org/folio/rest/impl/AccountsAPI.java
- src/test/java/org/folio/rest/impl/AccountsCancelActionAPITests.java
- src/test/java/org/folio/rest/impl/AccountsPayWaiveTransferAPITests.java
- src/test/java/org/folio/rest/impl/AccountsRefundAPITests.java
Resolves [MODFEE-247](https://issues.folio.org/browse/MODFEE-247)
> [MODFEE-247] Return remaining amount in action response

- ramls/actions/cancelActionRequest.json
Resolves: https://issues.folio.org/browse/MODFEE-250.
> Make comments field not required in CancelActionRequest

- src/main/java/org/folio/rest/impl/LostItemFeePoliciesAPI.java
- src/test/java/org/folio/rest/impl/LostItemFeePoliciesAPITest.java
Avoid entering values less then 0 to Lost item processing fee 
Add validation
Add tests
https://issues.folio.org/browse/MODFEE-253
> MODFEE-253 Lost item processing fee can be saved with a value less than 0

- pom.xml
- src/test/java/org/folio/migration/FeeFineTypesDefaultReferenceRecordsTest.java
- src/test/java/org/folio/rest/client/UsersClientTest.java
- src/test/java/org/folio/rest/domain/MonetaryValueSerializerTest.java
- src/test/java/org/folio/rest/impl/AccountsAPITest.java
- src/test/java/org/folio/rest/impl/AccountsBulkPayWaiveTransferAPITests.java
- src/test/java/org/folio/rest/impl/AccountsCancelActionAPITests.java
- src/test/java/org/folio/rest/impl/AccountsPayWaiveTransferAPITests.java
- src/test/java/org/folio/rest/impl/AccountsRefundAPITests.java
- src/test/java/org/folio/rest/impl/CashDrawerReconciliationReportTest.java
- src/test/java/org/folio/rest/impl/FeeFineActionsAPITest.java
- src/test/java/org/folio/rest/impl/FeeFinesAPITest.java
- src/test/java/org/folio/rest/impl/FinancialTransactionDetailReportTest.java
- src/test/java/org/folio/rest/impl/LostItemFeePoliciesAPITest.java
- src/test/java/org/folio/rest/impl/ManualBlockTemplatesAPITest.java
- src/test/java/org/folio/rest/impl/ManualBlocksAPITests.java
- src/test/java/org/folio/rest/impl/OverdueFinePoliciesAPITest.java
- src/test/java/org/folio/rest/impl/RefundReportTest.java
- src/test/java/org/folio/rest/impl/TenantRefAPITest.java
- src/test/java/org/folio/rest/impl/accountactionchecks/AccountsActionChecksAPITests.java
- src/test/java/org/folio/rest/impl/accountactionchecks/bulk/AccountsActionBulkCheckPayWaiveTransferAPITests.java
- src/test/java/org/folio/rest/impl/accountactionchecks/bulk/AccountsActionCheckBulkRefundAPITests.java
- src/test/java/org/folio/test/support/ApiTests.java
- src/test/java/org/folio/test/support/OkapiDeployment.java
- update tests using junit5 platform;
- fix broken tests and dependencies;
Resolves: [MODFEE-254](https://issues.folio.org/browse/MODFEE-254)
> MODFEE-254 update tests with junit5

- src/main/java/org/folio/rest/service/report/DateBasedReportService.java
- src/test/java/org/folio/rest/impl/FinancialTransactionDetailReportTest.java
[MODFEE-266](https://issues.folio.org/browse/MODFEE-266)
> [MODFEE-266] Add support for different loan date formats to Financial Transactions Report

- NEWS.md
- pom.xml
- src/main/java/org/folio/rest/service/report/DateBasedReportService.java
- src/test/java/org/folio/rest/impl/FinancialTransactionDetailReportTest.java
https://issues.folio.org/browse/MODFEE-268
> [MODFEE-268] Release 17.1.3

- pom.xml
- src/test/java/org/folio/migration/FeeFineTypesDefaultReferenceRecordsTest.java
- src/test/java/org/folio/rest/impl/LostItemFeePoliciesAPITest.java
- src/test/java/org/folio/rest/impl/OverdueFinePoliciesAPITest.java
[MODFEE-281](https://issues.folio.org/browse/MODFEE-281)
> MODFEE-281 Upgrade to RMB 35.0.0 and Vertx 4.3.3

- NEWS.md
- pom.xml
Resolves: [MODFEE-294](https://issues.folio.org/browse/MODFEE-294)
> [MODFEE-294] Release 18.1.0

- descriptors/ModuleDescriptor-template.json
- ramls/actual-cost-fee-fine-bill.json
- ramls/actual-cost-fee-fine.raml
- ramls/actual-cost-record.json
- ramls/examples/actual-cost-fee-fine-bill.sample
- ramls/examples/actual-cost-record.sample
- ramls/examples/actual-cost-records.sample
- src/main/java/org/folio/rest/service/ActualCostFeeFineBillingService.java
- src/test/java/org/folio/rest/impl/ActualCostFeeFineAPITest.java
Add billed amount to Actual Cost Record as `feeFine.billedAmount`.
https://issues.folio.org/browse/MODFEE-307
> MODFEE-307: Add billed amount to actual cost record

- NEWS.md
- pom.xml
https://issues.folio.org/browse/MODFEE-323
> MODFEE-323: Release mod-feesfines v18.2.0

- NEWS.md
- pom.xml
- src/main/java/org/folio/rest/client/ConfigurationClient.java
- src/main/java/org/folio/rest/domain/LocaleSettings.java
- src/test/java/org/folio/rest/impl/CashDrawerReconciliationReportTest.java
- src/test/java/org/folio/rest/impl/FeeFineReportsAPITestBase.java
- src/test/java/org/folio/rest/impl/FinancialTransactionDetailReportTest.java
- src/test/java/org/folio/rest/impl/RefundReportTest.java
- src/test/java/org/folio/test/support/EntityBuilder.java
Resolves: [MODFEE-330](https://issues.folio.org/browse/MODFEE-330) Release mod-feesfines v18.2.1
> MODFEE-330: Release mod-feesfines v18.2.1

- src/main/java/org/folio/rest/service/report/FinancialTransactionsDetailReportService.java
- src/main/java/org/folio/rest/service/report/RefundReportService.java
- review Financial transaction and Refund reports code and fix potential NPE
Resolves: [MODFEE-355](https://issues.folio.org/browse/MODFEE-355)
> MODFEE-355 Fix potential NPE

- Dockerfile
- Jenkinsfile
- pom.xml
- src/test/java/org/folio/rest/impl/ManualBlockTemplatesAPITest.java
Migrate module from Java 11 to Java 17. [MODFEE-357](https://issues.folio.org/browse/MODFEE-357)
https://wiki.folio.org/display/TC/JDK+17+and+Java+17
> [MODFEE-357] Migrate to Java 17

- src/main/resources/templates/db_scripts/schema.json
Resolves MODFEE-319
Add indexes to improve performance and avoid "search without index" warnings
> MODFEE-319 Add indexes for itemId, status.name

- descriptors/ModuleDescriptor-template.json
- ramls/accountdata.json
- src/test/java/org/folio/rest/impl/FeeFineActionsAPITest.java
- src/test/java/org/folio/rest/service/FeeFineChargeServiceTest.java
Resolves: [MODFEE-337](https://issues.folio.org/browse/MODFEE-337)
> [MODFEE-337] Mandatory "status" field in "accountdata" schema

- src/main/java/org/folio/rest/utils/PatronNoticeBuilder.java
- src/test/java/org/folio/rest/impl/FeeFineActionsAPITest.java
- src/test/java/org/folio/rest/utils/PatronNoticeBuilderTest.java
Purpose:
https://folio-org.atlassian.net/browse/MODFEE-370
Note: PR to add 'displaySummary' field to the item schema was merged previously:
https://github.com/folio-org/mod-feesfines/pull/286/files
> [MODORDERS-1017] - Add displaySummary field

- NEWS.md
- pom.xml
[MODFEE-377](https://folio-org.atlassian.net/browse/MODFEE-377)
> MODFEE-377: Release 19.1.0

- descriptors/ModuleDescriptor-template.json
[MODFEE-381](https://folio-org.atlassian.net/browse/MODFEE-381)
> MODFEE-381: Update interface holdings-storage to version 7.0

- descriptors/ModuleDescriptor-template.json
[MODFEE-386](https://folio-org.atlassian.net/browse/MODFEE-386)
> MODFEE-381: Add support for interface instance-storage 11.0

- NEWS.md
- pom.xml
Resolves: [MODFEE-389](https://folio-org.atlassian.net/browse/MODFEE-389)
> [MODFEE] Release 19.2.0

- descriptors/ModuleDescriptor-template.json
- pom.xml
https://folio-org.atlassian.net/browse/MODFEE-385
- adding permission module name as prefix
- fixing incorrect permissions
> [MODFEE-385] - Review and cleanup Module Descriptors for mod-feesfines

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
https://folio-org.atlassian.net/browse/MODFEE-385
> Bugfix release 19.2.1

- ramls/actual-cost-record.json
- src/test/java/org/folio/rest/impl/ActualCostFeeFineAPITest.java
[MODFEE-408](https://folio-org.atlassian.net/browse/MODFEE-408)
> MODFEE-408: Fix actual-cost-record schema

- NEWS.md
- pom.xml
Covers: [MODFEE-410](https://folio-org.atlassian.net/browse/MODFEE-410)
> [MODFEE] Release 19.3.0

- NEWS.md
- pom.xml
Resolves: [MODFEE-420](https://folio-org.atlassian.net/browse/MODFEE-420)
> MODFEE-420 Release 19.3.2
