src/main/java/org/folio/rest/impl/OverdueFinePoliciesAPI.java
src/test/java/org/folio/rest/impl/OverdueFinePoliciesAPITest.java

**Purpose**
Change error message in `mod-feesfines` as per new requirements
**Link**
[MODFEE-16](https://issues.folio.org/browse/MODFEE-16)

[MODFEE-16] Error message not displaying when duplicate policy name entered

---

Dockerfile
descriptors/ModuleDescriptor-template.json

Use new Alpine base docker image with more recent Java 8 (222) with +UseContainerSupport, and JAVA_OPTIONS MaxRAMPercentage to manage container memory.
See notes at [FOLIO-2358](https://issues.folio.org/browse/FOLIO-2358).

MODFEE-18 FOLIO-2358 manage container memory

---

pom.xml
reference-data/lost-item-fees-policies/lost-item-fee-policy.json
reference-data/overdue-fines-policies/overdue-fine-policy.json
src/main/java/org/folio/rest/impl/TenantRefAPI.java
src/test/java/org/folio/rest/impl/TenantRefAPITest.java
src/test/java/org/folio/rest/utils/OkapiClient.java

https://issues.folio.org/browse/MODFEE-23: Create Overdue Fine Policy and Lost Item Policy - Test data for snapshot/testing environments.
* Add sample overdue and lost-item policies to use them in circulation rules.
* Add tenant API.

MODFEE-23: Add sample overdue-fine and lost-item-fee policies

---

pom.xml

https://issues.folio.org/browse/MODFEE-24: Incorrect next release version.
The [release guidelines](https://dev.folio.org/guidelines/release-procedures/#prepare-and-perform-the-source-release) state that the next release version should the next minor or major version.
The next release of mod-feesfines should be `15.7.0` or `16.0.0` not `15.6.1`.

MODFEE-24: Set module version to 15.7.0.

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/rest/impl/TenantRefAPI.java

https://issues.folio.org/browse/MODFEE-25: Update tenant API version to 1.2
Updated `_tenant` API version to 1.2, because it is required to allow reference data uploading: https://github.com/folio-org/okapi/blob/master/doc/guide.md#tenant-parameters.

MODFEE-25: Upgrade tenant API version to 1.2 to allow reference data upload.

---

src/main/java/org/folio/rest/domain/FeeFineNoticeContext.java
src/test/java/org/folio/rest/domain/FeeFineNoticeContextTest.java

**Purpose**
Enable sending of patron notices for transfers.
**Approach**
Extend the list of fee/fine actions with transfers (full and partial).
**Links**
[MODFEE-20](https://issues.folio.org/browse/MODFEE-20)

[MODFEE-20] enable patron notice sending for transfers

---

src/main/java/org/folio/rest/domain/FeeFineNoticeContext.java
src/main/java/org/folio/rest/service/PatronNoticeService.java
src/test/java/org/folio/PatronNoticeTest.java
src/test/java/org/folio/rest/domain/FeeFineNoticeContextTest.java
src/test/java/org/folio/rest/impl/FeeFineActionsAPITest.java

**Purpose**
Enable sending of patron notices for error.
**Approach**
Extend the list of fee/fine actions with error.
Add token "fee.reasonForCancellation" to template
**Links**
[MODFEE-21](https://issues.folio.org/browse/MODFEE-21)

[MODFEE-21] Send patron notice for cancellation of fee/fine charge (due to error)

---

ramls/quantity.json
src/test/java/org/folio/rest/impl/OverdueFinePoliciesAPITest.java

**Purpose**
Fix `OverdueFinePolicy` validation for entities with fine amounts < 1.
**Approach**
Remove minimum value constraint from JSON-schema.
This resolves [MODFEE-34](https://issues.folio.org/browse/MODFEE-34).

[MODFEE-34] Can't save Overdue fine policy

---

pom.xml

The matching vert.x version for that rmb version is 3.8.x (latest is 3.8.5).
This is a minimal hotfix for b15.6 only.
Upgrading master to latest RMB is a separate task: https://issues.folio.org/browse/MODFEE-36

MODFEE-26: Upgrade module to raml module builder (RMB) 27.1.2

---

src/main/java/org/folio/rest/domain/FeeFineNoticeContext.java
src/test/java/org/folio/rest/domain/FeeFineNoticeContextTest.java

**Purpose**
Enable patron notices sending for Refunds.
**Approach**
Entend the list of fee/fine actions eligible for sending patron notices in `FeeFineNoticeContext`.
**Links**
Resolves [MODFEE-38](https://issues.folio.org/browse/MODFEE-38).

[MODFEE-38] Enabled patron notices sending for refunds

---

src/main/java/org/folio/rest/domain/FeeFineNoticeContext.java
src/test/java/org/folio/rest/domain/FeeFineNoticeContextTest.java

**Porpose**
Fix incorrect treatment of empty template IDs for action-based patron notices, which causes failures in `mod-notify` and results in patron notice emails not being delivered.
**Approach**
Removing custom templates from an existing fee/fine type on the UI results in their IDs not being removed, but saved as empty strings (`""`). These empty IDs should be treated as absent in `mod-feesfines`. The root cause of the issue will be handled in [UIU-1546](https://issues.folio.org/browse/UIU-1546).
**Links**
This PR resolves [MODFEE-41](https://issues.folio.org/browse/MODFEE-41).
UI part of the fix - [UIU-1546](https://issues.folio.org/browse/UIU-1546).

[MODFEE-41] Patron notices for actions and charges are not sent when templateId is an empty String

---

src/main/resources/templates/db_scripts/schema.json
src/test/java/org/folio/rest/impl/FeeFinesAPITest.java

**Purpose**
Currently, a user can not create manual fee/fine type for an owner, when the same type is already created for another owner.
**Approach**
Remove invalid `uniqueIndex` from schema, replace it with a composite index which allows unique combinations of `feeFineType` + `ownerId`.
**Links**
Original UI issue: [UIU-1547](https://issues.folio.org/browse/UIU-1547)
This PR resolves: [MODFEE-42](https://issues.folio.org/browse/MODFEE-42) and [UIU-1548](https://issues.folio.org/browse/UIU-1548)

[MODFEE-42] Unable to create duplicate fee/fine types for different owners

---

descriptors/ModuleDescriptor-template.json
ramls/accountdata.json
ramls/accounts.raml
ramls/holdings-record.json
ramls/holdings-records.json
ramls/item.json
ramls/items.json
ramls/uuid.json
src/main/java/org/folio/rest/client/InventoryClient.java
src/main/java/org/folio/rest/client/OkapiClient.java
src/main/java/org/folio/rest/client/PatronNoticeClient.java
src/main/java/org/folio/rest/impl/AccountsAPI.java
src/test/java/org/folio/rest/impl/AccountsAPITest.java
src/test/resources/__files/holdings.json
src/test/resources/__files/items.json

Adding two fields - holdingsRecordId and instanceId. The are populated on the fly for `/accounts` and `/account/{id}` requests.
This resolves MODFEE-48 which in turn helps to resolve UIU-1553 bug.

MODFEE-48 Add new fields fields to account

---

ramls/accountdata.json
src/test/java/org/folio/rest/impl/AccountsAPITest.java

Resolves [MODFEE-50](https://issues.folio.org/browse/MODFEE-50).
FE is trying to update these fields with `PUT /accounts/{id}` request, passing empty
strings. Though these fields are readonly and should be ignored by RMB, it still validates them which causes validation failures.

MODFEE-50 Remove readonly fields validation

---

src/main/java/org/folio/rest/utils/PatronNoticeBuilder.java
src/test/java/org/folio/rest/impl/FeeFineActionsAPITest.java
src/test/java/org/folio/rest/utils/PatronNoticeBuilderTest.java

**Purpose**: add missing token `feeCharge.additionalInfo`.
Resolves [MODFEE-72](https://issues.folio.org/browse/MODFEE-72).

[MODFEE-72] Add token `feeCharge.additionalInfo`

---

src/main/java/org/folio/rest/domain/logs/LogEventPayloadHelper.java
src/test/java/org/folio/rest/impl/AccountsBulkPayWaiveTransferAPITests.java
src/test/java/org/folio/rest/impl/AccountsPayWaiveTransferAPITests.java
src/test/java/org/folio/rest/impl/FeeFineActionsAPITest.java
src/test/java/org/folio/test/support/matcher/LogEventMatcher.java

[MODFEE-139](https://issues.folio.org/browse/MODFEE-139) - Fees/fines records in Circulation log do not contain item details
This PR fixes an issue by adding item info into log record payload

MODFEE-139 - Fees/fines records in Circulation log do not contain item details

---

descriptors/ModuleDescriptor-template.json
ramls/accounts.raml
ramls/actions/cancelActionRequest.json
src/main/java/org/folio/rest/domain/ActionRequest.java
src/main/java/org/folio/rest/service/action/CancelActionService.java
src/test/java/org/folio/rest/impl/AccountsCancelActionAPITests.java

https://issues.folio.org/browse/MODFEE-137 - Provide ability to specify cancellation reason in accounts/:id/cancel request.
* Bump `feesfines` API version to `16.1`
* Update `cancelActionRequest.json` schema with new `cancellationReason` property which defaulting to `Cancelled as error` value.
* Use the reason when an account is closed and set the reason to:
* `account.paymentStatus.name`
* `accountAction.typeAction`
* Add a test case to verify the new behavior.

MODFEE-137: Add ability to provide custom cancellation reason for an account.

---

ramls/manualblockdata.json

As [UIU-1911](https://issues.folio.org/browse/UIU-1911) specifies, manual patron blocks should have an optional field "block code". This code may be defined by block templates which were added by [MODFEE-133](https://issues.folio.org/browse/MODFEE-133).
This PR adds the optional field _code_ to the schema of manual blocks.
https://issues.folio.org/browse/MODFEE-145

MODFEE-145: Add property code to manual blocks

---

NEWS.md
descriptors/ModuleDescriptor-template.json
ramls/lost-item-fee-policy.json
ramls/lost-item-fee-policy.raml
src/test/java/org/folio/rest/impl/LostItemFeePoliciesAPITest.java

I added the requested fields to the RAML file for this policy type
this seems to make the build process automatically generate the
changes to the model and the underlying database.  I also inserted
the new fields in the lost item policy API test file.  Since this
file doesn't seem to check that any specific field exists in any
created policy, I didn't put in anything that specifically checks
for these fields either. However, I did confirm that that the fields
were present in the resulting posted policy by dumping the entire
response to screen and looking at it.  I also confirmed that if the
API was not expecting those fields or able to store them, it would
respond with a 422 error, which is not the case.
refs: https://issues.folio.org/browse/MODFEE-146

MODFEE-146: Store new aged to lost settings for recalled items

---

NEWS.md
descriptors/ModuleDescriptor-template.json

Some `modulePermissions` for the path `DELETE /accounts/{id}` were
incorrectly listed under `permissionsRequired` instead.
Fixes [MODFEE-151](https://issues.folio.org/browse/MODFEE-151)

MODFEE-151 correctly specify permissions

---

src/main/java/org/folio/rest/service/report/RefundReportService.java
src/test/java/org/folio/rest/impl/AccountsBulkPayWaiveTransferAPITests.java
src/test/java/org/folio/rest/impl/AccountsCancelActionAPITests.java
src/test/java/org/folio/rest/impl/AccountsPayWaiveTransferAPITests.java
src/test/java/org/folio/rest/impl/AccountsRefundAPITests.java
src/test/java/org/folio/rest/impl/FeeFineReportsAPITest.java
src/test/java/org/folio/rest/impl/accountactionchecks/bulk/AccountsActionCheckBulkRefundAPITests.java
src/test/java/org/folio/rest/utils/ResourceClients.java
src/test/java/org/folio/test/support/ApiTests.java

Resolves [MODFEE-170](https://issues.folio.org/browse/MODFEE-170).
The issue is caused by fee/fine actions repository returning entries in the wrong order, e.g. refund action is listed before payment. This was fixed by sorting account's action list by date.

MODFEE-170 Sort fee/fine actions by date

---

src/main/resources/templates/db_scripts/schema.json

Added two missing b-tree indexes for the field "userId" in the accounts and manualblocks tables.
I did not add an index for accounts.jsonb-->'status', as specified in the JIRA, because it is an enum table and only has a few values.

MODFEE-169: Add missing indexes

---

src/main/java/org/folio/rest/repository/FeeFineActionRepository.java
src/test/java/org/folio/rest/impl/accountactionchecks/bulk/AccountsActionCheckBulkRefundAPITests.java

Resolves [MODFEE-182](https://issues.folio.org/browse/MODFEE-182).
Remaining amount is not calculated correctly because of incorrect DB query.
Replace CQL `any (uuid1, uuid2)` kind of filter with more strict SQL `(accountId = uuid1 OR accountId = uuid2)`.

MODFEE-182 Fix Remaining amount calculation for refund action

---

src/main/java/org/folio/rest/impl/FeeFineActionsAPI.java
src/main/java/org/folio/rest/service/action/ActionService.java
src/test/java/org/folio/rest/impl/AccountsRefundAPITests.java
src/test/java/org/folio/test/support/matcher/LogEventMatcher.java

JIRA issue: https://issues.folio.org/browse/MODFEE-187
When creating new circulation action, like fees/fines - refunded partially, filtering by user barcode, item barcode or fee/fine drop down filters don't show actions
- Changed Refund and Credit actions to be processed by logEventService and published as FeeFineLogEvent
- Changed tests

MODFEE-187 - Search/filter on fees/fines not pulling recent circ log actions

---

pom.xml

Resolves [MODFEE-195](https://issues.folio.org/browse/MODFEE-195)
`maven-model` dependency shouldn't have `test` scope because it's used by pub-sub client utils.

MODFEE-195 Change maven-model dependency scope

---

src/main/java/org/folio/rest/domain/logs/LogEventPayloadHelper.java
src/test/java/org/folio/rest/impl/FeeFineActionsAPITest.java

[MODFEE-202](https://issues.folio.org/browse/MODFEE-202) - Circulation log record event should contain staff information content
* added "comments" field to the circulation log record event body
* updated unit tests

MODFEE-202 - Circulation log record event should contain staff information content

---

src/main/java/org/folio/rest/service/report/DateBasedReportService.java
src/test/java/org/folio/rest/impl/FeeFineReportsAPITestBase.java

Format of field loan DateTimeFormatter in DateBasedReportService was changed due to avoid error within creating "Financial transaction detail report"

MODFEE-206 change loanDateTimeFormatter

---

pom.xml
src/test/java/org/folio/rest/impl/LostItemFeePoliciesAPITest.java
src/test/java/org/folio/rest/impl/OverdueFinePoliciesAPITest.java

In the scope of the task on module upgrade, proper actions were fulfilled following instructions to update RMB
•	Updated RMB version
•	Updated Vertx version
•	Removed FOLIO fork of the vertx-sql-client and vertx-pg-client
•	Tests fixed
https://issues.folio.org/browse/MODFEE-236
https://github.com/folio-org/raml-module-builder/blob/master/doc/upgrading.md

MODFEE-236 Update RMB to v33.2.4

---

src/main/java/org/folio/rest/service/report/RefundReportService.java
src/test/java/org/folio/rest/impl/RefundReportTest.java

Resolves [MODFEE-249](https://issues.folio.org/browse/MODFEE-249)
Fixes Refund report for cases when there are refunds linked to same same account both inside and outside of the requested interval

MODFEE-249 Fix 500 error while exporting Refunds to process manually report

---

descriptors/ModuleDescriptor-template.json

mod-inventory-storage has new major interface versions:
instance-storage 9.0
holdings-storage 6.0
item-storage 10.0
mod-feesfines is not affected because the incompatible change is in the DELETE all APIs only that is not used by mod-feesfines. Changed APIs:
DELETE /inventory/instances
DELETE /inventory/items
DELETE /instance-storage/instances
DELETE /holdings-storage/holdings
DELETE /item-storage/items
Only the okapiInterfaces need to be bumped in "requires" section of ModuleDescriptor-template.json to support the new major versions.

MODFEE-270: instance-storage 9.0, holdings-storage 6.0, item-storage 10.0

---

descriptors/ModuleDescriptor-template.json
ramls/accountdata.json
ramls/examples/account.sample
src/test/java/org/folio/rest/impl/AccountsAPITest.java

- Add new optional field "processId" to fee/fine ("account") schema
Resolves: [MODFEE-275](https://issues.folio.org/browse/MODFEE-275)

[MODFEE-275] Add processId field to account schema

---

descriptors/ModuleDescriptor-template.json
ramls/inventory/instance.json

Some details about instance.json update:
Fetched latest version of instance.json from mod-inventory https://github.com/folio-org/mod-inventory/blob/master/ramls/instance.json
Left "$ref": "../raml-util/schemas/uuid.schema" for validation as it was in the original file for validation
Modified all "additionalProperties": false to "additionalProperties": true in order to be resilient to extra fields if any.

MODFEE-309 update instance-storage interface version and schema

---

src/main/java/org/folio/rest/client/ConfigurationClient.java
src/main/java/org/folio/rest/domain/LocaleSettings.java
src/test/java/org/folio/rest/impl/CashDrawerReconciliationReportTest.java
src/test/java/org/folio/rest/impl/FeeFineReportsAPITestBase.java
src/test/java/org/folio/rest/impl/FinancialTransactionDetailReportTest.java
src/test/java/org/folio/rest/impl/RefundReportTest.java
src/test/java/org/folio/test/support/EntityBuilder.java

- Fix the issue with inability to generate Financial Transaction Detail Report, Cash Drawer Reconciliation Report, and Refunds to Process Manually Report in Orchid Bugfest;
Resolves: [MODFEE-327](https://issues.folio.org/browse/MODFEE-327)
- fail configuration parsing if it's not correct;
- use the default configuration for this kind of scenario;
- add tests to cover this scenario for each report;

MODFEE-327 Add error handling for invalid configuration

---

src/main/java/org/folio/rest/utils/PatronNoticeBuilder.java
src/test/java/org/folio/rest/impl/FeeFineActionsAPITest.java
src/test/java/org/folio/rest/utils/PatronNoticeBuilderTest.java
src/test/java/org/folio/test/support/EntityBuilder.java

**Purpose**
This PR serves the purpose to add the value of Item.effectiveLocationDiscoveryDisplayName in the Notice Context which is required as per [https://issues.folio.org/browse/MODFEE-328](url) for Manual fee/fine charge + Manual fee/fine action (pay, waive, refund, transfer or cancel/error).
**Approach**
We already have the field discoveryDisplayName in Location Object so at the time of preparing Notice context
we are adding the above value and set it to the Item Context.
After this change, LocationDiscoveryDisplayName is populated in the Notices. Please find the Email Evidence below

MODFEE-328 Add the field "effectiveLocationDiscoveryDisplayName" to the Item Object in the Notice context

---

.github/workflows/api-doc.yml
.github/workflows/api-lint.yml
.github/workflows/api-schema-lint.yml
Jenkinsfile
README.md
ramls/accounts.raml

[FOLIO-3678](https://issues.folio.org/browse/FOLIO-3678)
Use GitHub Workflows for [api-lint](https://dev.folio.org/guides/api-lint/) and [api-schema-lint](https://dev.folio.org/guides/describe-schema/) and [api-doc](https://dev.folio.org/guides/api-doc/)
(instead of Jenkins-operated CI stages).

FOLIO-3678 MODFEE-348 Use GitHub Workflows api-lint and api-schema-lint and api-doc

---

ramls/overdue-fine-policy.json
ramls/overdue-fine-policy.raml
ramls/reminder-fees-policy.json
src/main/resources/templates/db_scripts/schema.json

PR would add a new optional section "reminderFeesPolicy" to the Overdue Fine Policy Schema.
The PR provides for adding a reminder fees schedule that is meant to kick in when a loan becomes overdue. At this stage, it does not contain any logic for handling any of these settings however. The PR is purely about extending the schema so far.
It's suggested to raised the version of Overdue Fine Policies API from 1.0 to 1.1 due to the new optional element.

MODFEE-345

---

pom.xml
src/main/java/org/folio/rest/impl/ManualBlockTemplatesAPI.java
src/test/java/org/folio/rest/impl/LostItemFeePoliciesAPITest.java
src/test/java/org/folio/rest/impl/OverdueFinePoliciesAPITest.java

Covers [MODFEE-375](https://folio-org.atlassian.net/browse/MODFEE-375)
Upgrade to RMB 35.2.0, Vertx 4.5.5, Spring 6.1.5
According to https://github.com/folio-org/raml-module-builder/blob/master/doc/upgrading.md#version-352, changed javax.validation package to jakarta.validation.

MODFEE-375 Upgrade to RMB 35.2.0, Vertx 4.5.5

---

src/main/java/org/folio/rest/domain/LoanRelatedFeeFineClosedEvent.java
src/main/java/org/folio/rest/service/AccountEventPublisher.java
src/main/java/org/folio/rest/service/AccountUpdateService.java
src/main/java/org/folio/rest/service/action/ActionService.java
src/test/java/org/folio/rest/impl/AccountsAPITest.java
src/test/java/org/folio/rest/impl/AccountsBulkPayWaiveTransferAPITests.java
src/test/java/org/folio/rest/impl/AccountsPayWaiveTransferAPITests.java

Steps to Reproduce:
1.  In circulation settings, set the lost item fee policy to charge a flat replacement fee, and a separate lost item processing fee.  Amounts don't matter.
2.  check out an item with this policy attached to a user.  I use barcode 10101 for testing, but i think most items in the system use this policy.
3.  Navigate to the user detail screen for that user and click on loans.  click down to the loan for the item you just checked out.  Declare the item lost. 
4. Go to fees/fines and pay the fine and processing fee for that item.
5.  Go back to loans and check the closed loan details screen for that loan. 
Expected result:
there should be one lost and paid transaction noted in the actions table.
Actual result:
system shows two separate lost and paid actions
Resolves: …

[MODFEE-380] Update feefine closed event publishing

---

descriptors/ModuleDescriptor-template.json

MODFEE-399
Add missing required interfaces.
Some required interfaces are not specified in Module Descriptor. This leads to excessive egress request routing though Kong, instead of direct calls to other module sidecars.
Sidecar logs:
`sidecar-mod-feesfines,/loan-types/2b94c631-fca9-4892-a730-03ee529ffe27,14`

MODFEE-399 Add missing required interfaces
